### ISSUE TITLE
Code correction for implementation.py

### ISSUE THREAD

**Issue by lucksd356** [michaeldorner/DecisionTrees#2]
96: trueBranch = growDecisionTreeFrom(bestSets[0], evaluationFunction)
97: falseBranch = growDecisionTreeFrom(bestSets[1], evaluationFunction)

**Comment by michaeldorner** [comment]
Sorry, I don't know what you mean.

**Comment by lucksd356** [comment]
To allow override of the default ‘entropy’ option, the following code is
needed at line 96:

trueBranch = growDecisionTreeFrom(bestSets[0], evaluationFunction) falseBranch
= growDecisionTreeFrom(bestSets[1], evaluationFunction)
